substitutions:
  TAG_NAME: trigger
steps:
  - name: gcr.io/cloud-builders/gcloud
    id: 'submit-build'
    waitFor: ['-']
    entrypoint: '/bin/bash'
    env:
      - "IMANDRA_DOCS_BUILDER=eu.gcr.io/imandra-dev/imandra-docs-builder:ccb0ab6adcb877d403b4c5b836c09c081e844a25"
    args:
      - '-c'
      - |
        mkdir -p tmp
        gsutil cp 'gs://imandra-dev-cloudbuilds/imandra-docs/cloudbuild.yaml' ./tmp/cloudbuild.yaml
        gcloud builds submit \
          'gs://imandra-dev-cloudbuilds/imandra-docs/imandra-docs-cloudbuild.tar.gz' \
          --config tmp/cloudbuild.yaml \
          --async \
          --substitutions="BRANCH_NAME=$BRANCH_NAME,COMMIT_SHA=$COMMIT_SHA,REPO_NAME=imandra-docs,TAG_NAME=build,_IMANDRA_DOCS_BUILDER=$$IMANDRA_DOCS_BUILDER"
